INHERIT: docs/mkdocs-base.yml

site_name: fast-minimum-variance
site_description: Fast minimum variance portfolio optimisation.
site_author: Jebel Quant Research
site_url: https://jebel-quant.github.io/fast_minimum_variance/
repo_url: https://github.com/Jebel-Quant/fast_minimum_variance
repo_name: Jebel-Quant/fast_minimum_variance
copyright: Copyright &copy; 2024–2026 Jebel Quant Research

docs_dir: docs

nav:
  - Home: index.md
  - API Reference: api.md
  - Notebooks:
    - Minimum Variance: notebooks/minvar.html
  - Reports:
    - Test Report: reports/html-report/report.html
    - Coverage Report: reports/html-coverage/index.html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Jebel-Quant/fast_minimum_variance

theme:
  icon:
    logo: material/chart-line

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
